# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Docker-in-docker

on:
  push:
    branches: [ "main" ]
    paths: .github/workflows/docker-in-docker.yml

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Docker
      run: |
        docker pull ubuntu
        docker system info
